---
title: "Simulations for heteroscedastic linear regression"
author: "Jackson Zhou"
date: "2022-10-09"
output: html_document
---

```{r Sourcing auxiliary functions}
library(tidyverse) # Data manipulation and plotting
library(rstan)     # Robust MCMC and diagnostics
library(EnvStats)  # Compute empirical densities

source("../EP-general-auxiliaries.R")
source("Heteroscedastic-auxiliaries.R")
```

```{r Generating random data}
set.seed(1)
n <- 120
p.1 <- 20
p.2 <- 6

mu.theta <- rep(0, p.1 + p.2)
Sigma.theta <- 10000*diag(p.1 + p.2)

X.1 <- cbind(rep(1, n), matrix(data = rnorm(n = n*(p.1 - 1)), nrow = n))
X.2 <- cbind(rep(1, n), matrix(data = rnorm(n = n*(p.2 - 1)), nrow = n))

beta.1 <- c(rbind(rep(2, p.1/2), rep(-2, p.1/2)))/p.1
beta.2 <- c(rbind(rep(2, p.2/2), rep(-2, p.2/2)))/p.2
theta <- c(beta.1, beta.2)

y <- rnorm(n, X.1%*%beta.1, sqrt(exp(X.2%*%beta.2)))
```

```{r Laplace approximation}
laplace.res <- laplace.approx(X.1, X.2, y, mu.theta, Sigma.theta, lambda.init = 0.5, maxit = 50000)
laplace.mu <- laplace.res$mu
laplace.Sigma <- laplace.res$Sigma
```

```{r EP approximation}
set.seed(1)
ep.res <- ep.approx(X.1, X.2, y, mu.theta, Sigma.theta, 
                    eta = 0.5, alpha = 1, Q.star = 0.01*diag(2), r.star = rep(0, 2), prec = 0,
                    max.passes = 200, tol.factor = Inf, stop.factor = Inf , abs.thresh = 0.5, 
                    rel.thresh = 0.9, delta.limit = Inf, patience = 40, verbose = T)
ep.mu <- ep.res$mu
ep.Sigma <- ep.res$Sigma
```

```{r MCMC approximation}
set.seed(1)
stan.res <- stan(file = "Heteroscedastic-model.stan",
                 data = list(N = n,
                             p_1 = p.1,
                             p_2 = p.2,
                             X_1 = X.1,
                             X_2 = X.2,
                             y = y,
                             mu_theta = mu.theta,
                             Sigma_theta = Sigma.theta),
                 chains = 1,
                 iter = 50000,
                 warmup = 5000,
                 init = "random")

mcmc.samples <- rstan::extract(stan.res)$theta
mcmc.mu <- colMeans(mcmc.samples)
mcmc.Sigma <- var(mcmc.samples)
```

```{r Comparing approximations}
for (j in 1:(p.1 + p.2)) {
  curve(demp(x, obs = mcmc.samples[, j]),
        from = mcmc.mu[j] - 5*sqrt(mcmc.Sigma[j, j]),
        to = mcmc.mu[j] + 5*sqrt(mcmc.Sigma[j, j]))
  abline(v = mcmc.mu[j], lty = 2)
  curve(dnorm(x, laplace.mu[j], sqrt(laplace.Sigma[j, j])), col = "blue", add = TRUE)
  curve(dnorm(x, ep.mu[j], sqrt(ep.Sigma[j, j])), col = "red", add = TRUE)
}
```
