---
title: "Simulations for random intercept linear regression"
author: "Jackson Zhou"
date: "2022-10-09"
output: html_document
---

```{r Sourcing auxiliary functions}
library(tidyverse) # Data manipulation and plotting
library(rstan)     # Robust MCMC and diagnostics
library(EnvStats)  # Compute empirical densities

source("../EP-general-auxiliaries.R")
source("Random-intercept-auxiliaries.R")
```

```{r Generating random data}
set.seed(1)
n <- 40
p <- 4
q <- 5

mu.beta.eg <- rep(0, p)
Sigma.beta.eg <- 10000*diag(p)

mu.tau.y.eg <- 0
sigma.2.tau.y.eg <- 10000

mu.tau.u.eg <- 0
sigma.2.tau.u.eg <- 10000

X.eg <- cbind(rep(1, n), matrix(data = rnorm(n = n*(p - 1)), nrow = n))
Z.eg <- as.matrix(bdiag(rep(list(rep(1, n/q)), q)))

beta.eg <- c(rbind(rep(2, p/2), rep(-2, p/2)))/p
tau.y.eg <- -1
tau.u.eg <- -0.5
u.eg <- rnorm(q, sd = exp(tau.u.eg))
y.eg <- rnorm(n, X.eg%*%beta.eg + Z.eg%*%u.eg, exp(tau.y.eg))
```

```{r EP approximation}
set.seed(1)
ep.res <- ep.approx(X.eg, Z.eg, y.eg, mu.beta.eg, Sigma.beta.eg, 
                    mu.tau.y.eg, sigma.2.tau.y.eg, mu.tau.u.eg, sigma.2.tau.u.eg,
                    eta = 0.5, alpha = 1,
                    max.passes = 200, tol.factor = Inf, stop.factor = Inf , abs.thresh = 0.5, 
                    rel.thresh = 0.9, delta.limit = Inf, patience = 40, verbose = T)
ep.mu <- ep.res$mu
ep.Sigma <- ep.res$Sigma
```

```{r MCMC approximation}
set.seed(1)
stan.res <- stan(file = "Random-intercept-model.stan",
                 data = list(N = n,
                             p = p,
                             q = q,
                             X = X.eg,
                             Z = Z.eg,
                             y = y.eg,
                             mu_beta = mu.beta.eg,
                             mu_tau_y = mu.tau.y.eg,
                             mu_tau_u = mu.tau.u.eg,
                             Sigma_beta = Sigma.beta.eg,
                             sigma_2_tau_y = sigma.2.tau.y.eg,
                             sigma_2_tau_u = sigma.2.tau.u.eg),
                 chains = 1,
                 iter = 50000,
                 warmup = 5000,
                 init = "random") 

mcmc.samples <- rstan::extract(stan.res)$theta
mcmc.mu <- colMeans(mcmc.samples)
mcmc.Sigma <- var(mcmc.samples)
```

```{r Comparing approximations}
for (j in 1:(p + q + 2)) {
  curve(demp(x, obs = mcmc.samples[, j]),
        from = mcmc.mu[j] - 5*sqrt(mcmc.Sigma[j, j]),
        to = mcmc.mu[j] + 5*sqrt(mcmc.Sigma[j, j]))
  abline(v = mcmc.mu[j], lty = 2)
  curve(dnorm(x, ep.mu[j], sqrt(ep.Sigma[j, j])), col = "red", add = TRUE)
}
```
