%% Simulations/benchmarks for lasso linear regression (VB)

num_each_type = 3;
num_sim = 50;
setting.mu_kappa = 0;
setting.sigma_2_kappa = 10000;
setting.lambda = 0.5;

options = optimoptions("fminunc",...
                       "MaxFunctionEvaluations",500000,...
                       "MaxIterations",500000);

% Simulations

for type_iter = 1:num_each_type
    results_table = table;
    for iteration = 1:num_sim
        disp(strcat("Current progress: Simulation ",...
                    string(type_iter),...
                    ", iteration ",...
                    string(iteration),...
                    " of ",...
                    string(num_sim)));

        data = readmatrix(strcat("Lasso-data/Sim-",...
                                 string(type_iter),...
                                 "-iter-",...
                                 pad(string(iteration),2,"left","0"),...
                                 ".csv"));

        p = size(data, 2) - 1;

        theta_init = fminunc(@(theta)-h_lasso(data,theta,setting),...
                             zeros(p+1,1), options);

        vb_res = CGVB(@grad_h_lasso,data,...
                      'NumParams',p+1,...
                      'Setting',setting,...
                      'LearningRate',0.0005,...
                      'NumSample',300,...
                      'MaxPatience',10,...
                      'MaxIter',600,...
                      'MeanInit',theta_init ,...
                      'GradWeight1',0.75,...
                      'GradWeight2',0.75,...
                      'WindowSize',10,...
                      'GradientMax',10);

        vb_mu = vb_res.Post.mu;
        vb_Sigma = vb_res.Post.Sigma;

        for j = 1:(p+1)
            row = table;
            row.iteration = iteration;
            row.j = j;
            row.mu = vb_mu(j);
            row.sigma_2 = vb_Sigma(j, j);
            results_table = [results_table; row];
        end
    end

    writetable(results_table,strcat("Lasso-results/Sim-",...
                                    string(type_iter),...
                                    "-res-VB.csv"));
end

% Benchmarks

for type_iter = 1:num_each_type
    results_table = table;

    disp(strcat("Current progress: Benchmark ",string(type_iter)));

    data = readmatrix(strcat("Lasso-data/Bench-",string(type_iter),".csv"));
    p = size(data, 2) - 1;

    theta_init = fminunc(@(theta)-h_lasso(data,theta,setting),...
                         zeros(p+1,1), options);

    vb_res = CGVB(@grad_h_lasso,data,...
                  'NumParams',p+1,...
                  'Setting',setting,...
                  'LearningRate',0.0005,...
                  'NumSample',300,...
                  'MaxPatience',10,...
                  'MaxIter',600,...
                  'MeanInit',theta_init ,...
                  'GradWeight1',0.75,...
                  'GradWeight2',0.75,...
                  'WindowSize',10,...
                  'GradientMax',10);

    vb_mu = vb_res.Post.mu;
    vb_Sigma = vb_res.Post.Sigma;

    for j = 1:(p+1)
            row = table;
            row.j = j;
            row.mu = vb_mu(j);
            row.sigma_2 = vb_Sigma(j, j);
            results_table = [results_table; row];
    end

    writetable(results_table,strcat("Lasso-results/Bench-",...
                                    string(type_iter),...
                                    "-res-VB.csv"));
end
